### ISSUE TITLE
The publication should contain the pages.

### ISSUE THREAD

**Issue by shengyudingli** [RyuAsuka/ryuasuka.github.io#1]
The publication should contain the pages.

Jiewen Mao, Weijun Deng, Fuke Shen:
DDoS Flooding Attack Detection Based on Joint-Entropy with Multiple Traffic Features. TrustCom/BigDataSE 2018: 237-243

**Comment by RyuAsuka** [comment]
OK. I used the reference via Google Scholar and I didn't noticed the MLA format not containing page numbers.
